lnnrtwttkhn/version-control-book

chapters/intro-version-control.qmd
functions.R
references.bib

I managed to find some typos. Also changed the link to the Turing way tutorial, should look nicer now.
One more idea of me would be to already  include some disadvantages of git to "take the wind out of the sails".
Merging to "editexisting" since it had the most recent version of the chapter.

Update to intro chapter

---

chapters/command-line.qmd
chapters/installation-setup.qmd
cheatsheet.json

to prepare for session 2 of this course, we make updates mainly to the CLI chapters.
fixes #51

updates to the CLI chapter

---

_quarto.yml
chapters/first-steps-git.qmd
chapters/github-intro.qmd
chapters/installation-setup.qmd
chapters/installation.qmd
chapters/setup.qmd

Updates for session three

---

chapters/first-steps-git.qmd

This adds content to the basics chapter, originally planned for session 4, as discussed in #58 
Let me know what you think, when you have the time @lnnrtwttkhn

Update Basics chapter

---

_quarto.yml
chapters/branches.qmd
chapters/command-line.qmd
chapters/first-steps-git.qmd
chapters/github-intro.qmd
chapters/setup.qmd
chapters/stashing-rebasing.qmd
cheatsheet.json
misc/cheatsheet.qmd

This adds a complete cheatsheet to the "misc" section, as proposed in #49

Add complete cheatsheet

---

chapters/branches.qmd
chapters/first-steps-git.qmd
chapters/github-intro.qmd

Update for branches session in layout and content before next weeks session

Update branches chapter

---

chapters/github-intro.qmd

Adds some things discussed in https://github.com/lnnrtwttkhn/version-control-book/issues/77

Update GitHub chapter 

---

chapters/intermediate-commands.qmd
cheatsheet.json

- Added partial commits from command Line #69 
- Added Git reset

Update "Intermediate commands" chapter

---

_variables.yml
index.qmd

Adds first draft of a preface for the book, let me know what you think is missing

Draft of Preface

---

index.qmd

This adds testimonials of students the preface as discussed in #107.
I found two quotes we could use in the feedback to the course
fixes #107

Add testimonials of students

---

_variables.yml
chapters/github-intro.qmd

Also includes info about CONTRIBUTION.md. Fixes #86, #83

Expand section about README.md

---

index.qmd

Added a small "origin" section for the logo in the preface, also giving credits.  Fixes #129

Add section about logo origin

---

chapters/branches.qmd

fixes #131. Was able to retrieve cheatsheet and acknowledgements, they got lost in an older commit

add cheatsheet and acknowledgements to branches chapter

---

chapters/first-steps-git.qmd
chapters/installation.qmd
chapters/intermediate-commands.qmd
chapters/rewriting-history.qmd
chapters/setup.qmd

Add Images to chapters for content pages. Also adds the bad commits comic to basics chapter. Fixes #109 and #98

Add Images to chapters for content pages

---

.github/workflows/publish.yml
Makefile
misc/contributing.qmd

update make: update variable names, add make render, preview, deploy

---

chapters/setup.qmd
cheatsheet.json
exercises/_exercises-setup.qmd

Add some details about Vim and exercises to the Setup chapter, as discussed in #80.

Add content to setup chapter

---

chapters/branches.qmd
exercises/_exercises-branches.qmd

Add Explanation that:
- Switching to new branch only possible after first commit
-  Uncommited changes switch to new branch
Like collected in #80.
Also some small wording changes.

Add content to branches chapter (e.g., how to deal with uncommited changes before branch switch)

---

_variables.yml
chapters/command-line.qmd
exercises/_exercises-cli.qmd
objectives/_objectives-cli.qmd

Small updates to the command line chapter.
- Makes examples consistent with recipes example
- Update objectives + exercises

Update Command Line chapter

---

chapters/first-steps-git.qmd

Add short gitkeep section

---

chapters/command-line.qmd
chapters/setup.qmd

add faqs from session 03 

---

chapters/branches.qmd
cheatsheet.json
exercises/_exercises-branches.qmd
objectives/_objectives-branches.qmd
references.bib

Small updates to branches chapter:
- Updates exercises
- Adds names to code blocks #168
- Disables copy button in output code blocks #171
- minor edits throughout

update branches chapter: update exercuses, add names to code blocks, disable code copy buttons, minor content edits

---

chapters/command-line.qmd
cheatsheet.json

This add a short section on saving  Command Line history.

Add  short section on saving  Command Line history

---

chapters/first-steps-git.qmd

update section on .gitignore

---

chapters/github-intro.qmd

As discussed in an [Issue](https://github.com/lnnrtwttkhn/version-control-course-uhh-ss24/issues/25), updated the GitHub intro question with question asked in session 08.

Update questions from Session 08 to GitHub chapters

---

chapters/setup.qmd

add guardrail to prevent git repos in home directories, fix #184

---

cheatsheet.json

I would probably use this PR to add a few more fixes ...

fix cheatsheet

---

chapters/tags-and-releases.qmd

Small improvements to  tags and releases chapter 

---

chapters/command-line.qmd

Replace all zsh code chunks that are executed with bash, fix #218

---

_variables.yml
chapters/issues.qmd
chapters/setup.qmd
chapters/tags-and-releases.qmd
index.qmd

This adds:
- callout box concerning privy in setup chapter (#240)
- scientific use cases to issues chapter (#242)
- more motivation to preface (#227)
- explanation of HTML vs PDF version of book to preface (#222)
- explanation of how to tag older commit to tags/release chapter (#205)
Fixes #240 #242 #222 #205

Various (minor) additions

---

chapters/command-line.qmd
cheatsheet.json
objectives/_objectives-cli.qmd

This adds some content to the cli chapter
- Fixes #160 
- Fixes most of #215 (everything except screenshots from Windows device)
- Fixes #234

Minor improvements for cli chapter

---

chapters/setup.qmd

Minor improvement in setup chapter

---

chapters/first-steps-git.qmd
chapters/git-essentials.qmd

Adds a best practices section (#279). 
I included 9 points, do you think there is something missing @lnnrtwttkhn?
fixes #279

Add best practices section

---

cheatsheet.json

Update cheatsheet.json, see #295

---

chapters/intro-version-control.qmd

replaced "One"with "Once"and "you"with "your"
Fixes #284

fix typos#284

---

chapters/tags-and-releases.qmd

Added missing info to the -f flag for tags. Fixes #299

Add info to tag flag -f

---

chapters/remotes-intro.qmd

Added some more explanation in order to hopefully make fetching more clear to readers. This partially solves #298. An illustration is still missing though and would I think be helpful.

Add example and clarify fetching

---

chapters/remotes-intro.qmd

Answering some questions that came up in the "Remotes: Introduction" session of the UHH EUR course, here https://github.com/lnnrtwttkhn/version-control-course-uhh-eur-ws24/issues/29

Minor additions in Remotes Introduction chapter

---

chapters/github-advanced.qmd
objectives/_objectives-github-advanced.qmd

- Moved forking to bottom
- Integrated PR from fork into section about forking

Reordering of sections in GitHub Advanced chapter

---

misc/resources.qmd
references.bib

Added coderefinery to resources page and to references.
Fixes #343

Add CodeRefinery to resources
